### ISSUE TITLE
Wildcarding excluded files

### ISSUE THREAD

**Issue by jewkesy** [JulioGold/smart-zip#1]
How can I ignore all files with a given extension?

I've tried: -

```
var regexExcludes = ['*.zip'];
```

but get the following error: -

```
    if (file.match(regexExcludes[i])) {
                             ^
SyntaxError: Invalid regular expression: /*.zip/: Nothing to repeat
```

**Comment by jewkesy** [comment]
Sorry, my mistake.  

```
var regexExcludes = ['.zip'];
```

works as I expected

**Comment by JulioGold** [comment]
Hi jewkesy, i forgot to put it, but the exclusion works with regular expression over the file names.
Thanks for issue
